FROM almalinux:9
# ADD https://raw.githubusercontent.com/MEDASANI-CHARAN/terraform-aws-vpc/refs/heads/main/vpc.tf /tmp/session-vpc.tf
# ADD sample-1 /tmp/
ADD https://raw.githubusercontent.com/MEDASANI-CHARAN/dockerfiles/refs/heads/main/COPY/Dockerfile /tmp/Dockerfile
CMD ["sleep", "100"]